+----------+----------+---------+---------+
|   Used   |  Quota   | Percent |  Files  |
+----------+----------+---------+---------+
| 49.49 GB | 50.00 GB |  98.99% | 622,794 |
+----------+----------+---------+---------+

+-----------+----------+----------+--------+-----------+-------------+---------+
|     FS    |   Used   |  Quota   | Used % |   Files   | Files Quota | Files % |
+-----------+----------+----------+--------+-----------+-------------+---------+
|    data   | 9.10 TB  | 10.00 TB | 90.00% |  550,832  |  4,096,000  |  13.00% |
|  scratch4 | 9.81 TB  | 10.00 TB | 98.00% | 1,550,762 |  5,242,880  |  29.00% |
| scratch16 | 19.38 TB | 20.00 TB | 96.00% | 1,566,392 |  20,480,000 |  7.00%  |
+-----------+----------+----------+--------+-----------+-------------+---------+

Consider completing our user survey to provide feedback to help improve the cluster: https://jh.qualtrics.com/jfe/form/SV_bQOKO9M7xQFmwAu

The following have been reloaded with a version change:
  1) openmpi/3.1.6 => openmpi/4.1.6

Sat Oct 18 08:15:05 EDT 2025
Running "module reset". Resetting modules to system default. The following $MODULEPATH directories have been removed: None

The following have been reloaded with a version change:
  1) openmpi/4.1.6 => openmpi/3.1.6


Currently Loaded Modules:
  1) gcc/9.3.0       3) slurm/19.05.7   5) lua/5.4.4       7) git/2.28.0
  2) openmpi/3.1.6   4) lmod/8.7.24     6) helpers/0.1.1   8) standard/2020.10
/data/pclancy3/yi/flare-data/1-Cr-Sb2Te3/3.fine-tuning/AI4MAT25/MigrationBench/examples/Sb2Te3_Cr_doped/04_mlff_training/srun
/data/pclancy3/yi/.conda/envs/mace/lib/python3.9/site-packages/e3nn/o3/_wigner.py:10: UserWarning: Environment variable TORCH_FORCE_NO_WEIGHTS_ONLY_LOAD detected, since the`weights_only` argument was not explicitly passed to `torch.load`, forcing weights_only=False.
  _Jd, _W3j_flat, _W3j_indices = torch.load(os.path.join(os.path.dirname(__file__), 'constants.pt'))
cuequivariance or cuequivariance_torch is not available. Cuequivariance acceleration will be disabled.
2025-10-18 08:15:56.178 INFO: ===========VERIFYING SETTINGS===========
2025-10-18 08:15:56.179 WARNING: All of hidden_irreps, num_channels and max_L are specified
2025-10-18 08:15:56.179 WARNING: Using num_channels and max_L to create hidden_irreps: 32x0e+32x1o.
2025-10-18 08:15:56.179 INFO: Stage Two is activated as start_stage_two was defined
2025-10-18 08:15:56.179 INFO: MACE version: 0.3.12
2025-10-18 08:15:56.314 INFO: CUDA version: 11.8, CUDA device: 0
/data/pclancy3/yi/.conda/envs/mace/lib/python3.9/site-packages/mace/cli/run_train.py:149: UserWarning: Environment variable TORCH_FORCE_NO_WEIGHTS_ONLY_LOAD detected, since the`weights_only` argument was not explicitly passed to `torch.load`, forcing weights_only=False.
  model_foundation = torch.load(
2025-10-18 08:15:58.671 INFO: Using foundation model /data/pclancy3/yi/flare-data/1-Cr-Sb2Te3/3.fine-tuning/2-layer/MACE-omat/MACE-matpes-pbe-omat-ft.model as initial checkpoint.
2025-10-18 08:15:58.673 WARNING: Using multiheads finetuning with a foundation model that is not a Materials Project model, need to provied a path to a pretraining file with --pt_train_file.
2025-10-18 08:15:58.673 INFO: ===========LOADING INPUT DATA===========
2025-10-18 08:15:58.673 INFO: Using heads: ['default']
2025-10-18 08:15:58.673 INFO: =============    Processing head default     ===========
2025-10-18 08:15:58.753 WARNING: Since ASE version 3.23.0b1, using forces_key 'forces' is no longer safe when communicating between MACE and ASE. We recommend using a different key, rewriting 'forces' to 'REF_forces'. You need to use --forces_key='REF_forces' to specify the chosen key name.
2025-10-18 08:15:58.757 WARNING: Configuration '28' is marked as 'IsolatedAtom' but does not contain an energy. Zero energy will be used.
2025-10-18 08:15:58.757 WARNING: Configuration '29' is marked as 'IsolatedAtom' but does not contain an energy. Zero energy will be used.
2025-10-18 08:15:58.757 WARNING: Configuration '30' is marked as 'IsolatedAtom' but does not contain an energy. Zero energy will be used.
2025-10-18 08:15:58.760 INFO: Using isolated atom energies from training file
2025-10-18 08:15:58.761 INFO: Training file 1/1 [28 configs, 0 energy, 28 forces, 28 stresses] loaded from '../data/data_neb/train.xyz'
2025-10-18 08:15:58.761 INFO: Total training set [28 configs, 0 energy, 28 forces, 28 stresses]
2025-10-18 08:15:58.786 WARNING: Since ASE version 3.23.0b1, using forces_key 'forces' is no longer safe when communicating between MACE and ASE. We recommend using a different key, rewriting 'forces' to 'REF_forces'. You need to use --forces_key='REF_forces' to specify the chosen key name.
2025-10-18 08:15:58.787 INFO: Validation file 1/1 [3 configs, 0 energy, 3 forces, 3 stresses] loaded from '../data/data_neb/valid.xyz'
2025-10-18 08:15:58.787 INFO: Total validation set [3 configs, 0 energy, 3 forces, 3 stresses]
2025-10-18 08:15:58.810 WARNING: Since ASE version 3.23.0b1, using forces_key 'forces' is no longer safe when communicating between MACE and ASE. We recommend using a different key, rewriting 'forces' to 'REF_forces'. You need to use --forces_key='REF_forces' to specify the chosen key name.
2025-10-18 08:15:58.811 INFO: Test file 1/1 [4 configs, 0 energy, 4 forces, 4 stresses] loaded from '../data/data_neb/test.xyz'
2025-10-18 08:15:58.811 INFO: Total test set (4 configs):
2025-10-18 08:15:58.811 INFO: Default_default: 4 configs, 0 energy, 4 forces, 4 stresses
2025-10-18 08:15:58.811 INFO: Total number of configurations: train=28, valid=3, tests=[Default_default: 4],
2025-10-18 08:15:58.811 ERROR: Batch size (32) is larger than the number of training data (28)
2025-10-18 08:15:58.812 WARNING: Validation batch size (16) is larger than the number of validation data (3)
2025-10-18 08:15:58.812 INFO: Atomic Numbers used: [np.int64(24), np.int64(51), np.int64(52)]
2025-10-18 08:15:58.812 INFO: Atomic Energies used (z: eV) for head default: {24: 0.0, 51: 0.0, 52: 0.0}
2025-10-18 08:15:58.812 INFO: Processing datasets for head 'default'
2025-10-18 08:15:58.848 INFO: Combining 1 list datasets for head 'default'
2025-10-18 08:15:58.852 INFO: Combining 1 list datasets for head 'default_valid'
2025-10-18 08:15:58.852 INFO: Combined validation datasets for default
2025-10-18 08:15:58.852 INFO: Head 'default' training dataset size: 28
2025-10-18 08:15:58.855 INFO: Computing average number of neighbors
Traceback (most recent call last):
  File "/data/pclancy3/yi/.conda/envs/mace/bin/mace_run_train", line 8, in <module>
    sys.exit(main())
  File "/data/pclancy3/yi/.conda/envs/mace/lib/python3.9/site-packages/mace/cli/run_train.py", line 72, in main
    run(args)
  File "/data/pclancy3/yi/.conda/envs/mace/lib/python3.9/site-packages/mace/cli/run_train.py", line 700, in run
    args.avg_num_neighbors = get_avg_num_neighbors(head_configs, args, train_loader, device)
  File "/data/pclancy3/yi/.conda/envs/mace/lib/python3.9/site-packages/mace/tools/scripts_utils.py", line 588, in get_avg_num_neighbors
    avg_num_neighbors = modules.compute_avg_num_neighbors(train_loader)
  File "/data/pclancy3/yi/.conda/envs/mace/lib/python3.9/site-packages/mace/modules/utils.py", line 366, in compute_avg_num_neighbors
    torch.cat(num_neighbors, dim=0).type(torch.get_default_dtype())
RuntimeError: torch.cat(): expected a non-empty list of Tensors
Sat Oct 18 08:15:59 EDT 2025
