+----------+----------+---------+---------+
|   Used   |  Quota   | Percent |  Files  |
+----------+----------+---------+---------+
| 49.49 GB | 50.00 GB |  98.99% | 622,812 |
+----------+----------+---------+---------+

+-----------+----------+----------+--------+-----------+-------------+---------+
|     FS    |   Used   |  Quota   | Used % |   Files   | Files Quota | Files % |
+-----------+----------+----------+--------+-----------+-------------+---------+
|    data   | 9.10 TB  | 10.00 TB | 90.00% |  550,968  |  4,096,000  |  13.00% |
|  scratch4 | 9.81 TB  | 10.00 TB | 98.00% | 1,550,762 |  5,242,880  |  29.00% |
| scratch16 | 19.38 TB | 20.00 TB | 96.00% | 1,566,392 |  20,480,000 |  7.00%  |
+-----------+----------+----------+--------+-----------+-------------+---------+

Consider completing our user survey to provide feedback to help improve the cluster: https://jh.qualtrics.com/jfe/form/SV_bQOKO9M7xQFmwAu

The following have been reloaded with a version change:
  1) openmpi/3.1.6 => openmpi/4.1.6

Sat Oct 18 14:06:39 EDT 2025
Running "module reset". Resetting modules to system default. The following $MODULEPATH directories have been removed: None

The following have been reloaded with a version change:
  1) openmpi/4.1.6 => openmpi/3.1.6


Currently Loaded Modules:
  1) gcc/9.3.0       3) slurm/19.05.7   5) lua/5.4.4       7) git/2.28.0
  2) openmpi/3.1.6   4) lmod/8.7.24     6) helpers/0.1.1   8) standard/2020.10
/data/pclancy3/yi/flare-data/1-Cr-Sb2Te3/3.fine-tuning/AI4MAT25/mlff-benchmark-cr-sb2te3/examples/Sb2Te3_Cr_doped/04_mlff_training/srun
/data/pclancy3/yi/.conda/envs/mace/lib/python3.9/site-packages/e3nn/o3/_wigner.py:10: UserWarning: Environment variable TORCH_FORCE_NO_WEIGHTS_ONLY_LOAD detected, since the`weights_only` argument was not explicitly passed to `torch.load`, forcing weights_only=False.
  _Jd, _W3j_flat, _W3j_indices = torch.load(os.path.join(os.path.dirname(__file__), 'constants.pt'))
cuequivariance or cuequivariance_torch is not available. Cuequivariance acceleration will be disabled.
2025-10-18 14:07:30.669 INFO: ===========VERIFYING SETTINGS===========
2025-10-18 14:07:30.702 WARNING: All of hidden_irreps, num_channels and max_L are specified
2025-10-18 14:07:30.702 WARNING: Using num_channels and max_L to create hidden_irreps: 32x0e+32x1o.
2025-10-18 14:07:30.702 INFO: Stage Two is activated as start_stage_two was defined
2025-10-18 14:07:30.703 INFO: MACE version: 0.3.12
2025-10-18 14:07:30.840 INFO: CUDA version: 11.8, CUDA device: 0
/data/pclancy3/yi/.conda/envs/mace/lib/python3.9/site-packages/mace/cli/run_train.py:149: UserWarning: Environment variable TORCH_FORCE_NO_WEIGHTS_ONLY_LOAD detected, since the`weights_only` argument was not explicitly passed to `torch.load`, forcing weights_only=False.
  model_foundation = torch.load(
2025-10-18 14:07:32.318 INFO: Using foundation model /data/pclancy3/yi/flare-data/1-Cr-Sb2Te3/3.fine-tuning/2-layer/MACE-omat/MACE-matpes-pbe-omat-ft.model as initial checkpoint.
2025-10-18 14:07:32.320 WARNING: Using multiheads finetuning with a foundation model that is not a Materials Project model, need to provied a path to a pretraining file with --pt_train_file.
2025-10-18 14:07:32.320 INFO: ===========LOADING INPUT DATA===========
2025-10-18 14:07:32.320 INFO: Using heads: ['default']
2025-10-18 14:07:32.320 INFO: =============    Processing head default     ===========
2025-10-18 14:07:32.378 WARNING: Since ASE version 3.23.0b1, using energy_key 'energy' is no longer safe when communicating between MACE and ASE. We recommend using a different key, rewriting 'energy' to 'REF_energy'. You need to use --energy_key='REF_energy' to specify the chosen key name.
2025-10-18 14:07:32.382 WARNING: Since ASE version 3.23.0b1, using forces_key 'forces' is no longer safe when communicating between MACE and ASE. We recommend using a different key, rewriting 'forces' to 'REF_forces'. You need to use --forces_key='REF_forces' to specify the chosen key name.
2025-10-18 14:07:32.389 INFO: Using isolated atom energies from training file
2025-10-18 14:07:32.390 INFO: Training file 1/1 [28 configs, 28 energy, 28 forces, 28 stresses] loaded from '../data/data_neb/train.xyz'
2025-10-18 14:07:32.390 INFO: Total training set [28 configs, 28 energy, 28 forces, 28 stresses]
2025-10-18 14:07:32.419 WARNING: Since ASE version 3.23.0b1, using energy_key 'energy' is no longer safe when communicating between MACE and ASE. We recommend using a different key, rewriting 'energy' to 'REF_energy'. You need to use --energy_key='REF_energy' to specify the chosen key name.
2025-10-18 14:07:32.420 WARNING: Since ASE version 3.23.0b1, using forces_key 'forces' is no longer safe when communicating between MACE and ASE. We recommend using a different key, rewriting 'forces' to 'REF_forces'. You need to use --forces_key='REF_forces' to specify the chosen key name.
2025-10-18 14:07:32.420 INFO: Validation file 1/1 [3 configs, 3 energy, 3 forces, 3 stresses] loaded from '../data/data_neb/valid.xyz'
2025-10-18 14:07:32.420 INFO: Total validation set [3 configs, 3 energy, 3 forces, 3 stresses]
2025-10-18 14:07:32.460 WARNING: Since ASE version 3.23.0b1, using energy_key 'energy' is no longer safe when communicating between MACE and ASE. We recommend using a different key, rewriting 'energy' to 'REF_energy'. You need to use --energy_key='REF_energy' to specify the chosen key name.
2025-10-18 14:07:32.461 WARNING: Since ASE version 3.23.0b1, using forces_key 'forces' is no longer safe when communicating between MACE and ASE. We recommend using a different key, rewriting 'forces' to 'REF_forces'. You need to use --forces_key='REF_forces' to specify the chosen key name.
2025-10-18 14:07:32.462 INFO: Test file 1/1 [4 configs, 4 energy, 4 forces, 4 stresses] loaded from '../data/data_neb/test.xyz'
2025-10-18 14:07:32.462 INFO: Total test set (4 configs):
2025-10-18 14:07:32.462 INFO: Default_default: 4 configs, 4 energy, 4 forces, 4 stresses
2025-10-18 14:07:32.462 INFO: Total number of configurations: train=28, valid=3, tests=[Default_default: 4],
2025-10-18 14:07:32.462 ERROR: Batch size (32) is larger than the number of training data (28)
2025-10-18 14:07:32.462 WARNING: Validation batch size (16) is larger than the number of validation data (3)
2025-10-18 14:07:32.463 INFO: Atomic Numbers used: [np.int64(24), np.int64(51), np.int64(52)]
2025-10-18 14:07:32.463 INFO: Atomic Energies used (z: eV) for head default: {24: -2270.518789079322, 51: -1908.633351763048, 52: -2369.398259284361}
2025-10-18 14:07:32.463 INFO: Processing datasets for head 'default'
2025-10-18 14:07:32.497 INFO: Combining 1 list datasets for head 'default'
2025-10-18 14:07:32.500 INFO: Combining 1 list datasets for head 'default_valid'
2025-10-18 14:07:32.500 INFO: Combined validation datasets for default
2025-10-18 14:07:32.501 INFO: Head 'default' training dataset size: 28
2025-10-18 14:07:32.501 INFO: Computing average number of neighbors
Traceback (most recent call last):
  File "/data/pclancy3/yi/.conda/envs/mace/bin/mace_run_train", line 8, in <module>
    sys.exit(main())
  File "/data/pclancy3/yi/.conda/envs/mace/lib/python3.9/site-packages/mace/cli/run_train.py", line 72, in main
    run(args)
  File "/data/pclancy3/yi/.conda/envs/mace/lib/python3.9/site-packages/mace/cli/run_train.py", line 700, in run
    args.avg_num_neighbors = get_avg_num_neighbors(head_configs, args, train_loader, device)
  File "/data/pclancy3/yi/.conda/envs/mace/lib/python3.9/site-packages/mace/tools/scripts_utils.py", line 588, in get_avg_num_neighbors
    avg_num_neighbors = modules.compute_avg_num_neighbors(train_loader)
  File "/data/pclancy3/yi/.conda/envs/mace/lib/python3.9/site-packages/mace/modules/utils.py", line 366, in compute_avg_num_neighbors
    torch.cat(num_neighbors, dim=0).type(torch.get_default_dtype())
RuntimeError: torch.cat(): expected a non-empty list of Tensors
Sat Oct 18 14:07:33 EDT 2025
